version: 2
updates:
  # update github action packages
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
  # update pnpm packages
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'weekly'
  # update go packages
  - package-ecosystem: gomod
    directory: '/'
    schedule:
      interval: 'weekly'
